language: python
 
python:
  - '2.7'
 
before_script:
  - wget http://googleappengine.googlecode.com/files/google_appengine_1.8.9.zip -nv
  - unzip -q google_appengine_1.8.9.zip

script: './.travis-script.sh'
