application: dothiv-registry
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /_ah/queue/deferred
  script: $PYTHON_LIB/google/appengine/ext/deferred/handler.py
  login: admin
- url: /.*
  script: main.application
  secure: always

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

builtins:
- deferred: on